# Generated by Django 4.2.30 on 2026-08-02 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.CharField(max_length=500)),
                ("tags_json", models.TextField(default="[]")),
                (
                    "version_tag",
                    models.CharField(
                        blank=True,
                        help_text="Version of the app under test this test is associated with",
                        max_length=100,
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = use the runner default from config.json",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "archived",
                    models.BooleanField(
                        default=False,
                        help_text="File disappeared from tests/; history kept",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["test_id"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("days_json", models.TextField(default="[]")),
                ("time_of_day", models.TimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("last_fired", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.group",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="core.test",
                    ),
                ),
            ],
            options={
                "ordering": ["time_of_day"],
            },
        ),
        migrations.AddField(
            model_name="group",
            name="tests",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="core.test"
            ),
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "manual"),
                            ("selection", "selection"),
                            ("group", "group"),
                            ("schedule", "schedule"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("passed", "passed"),
                            ("failed", "failed"),
                            ("error", "error"),
                            ("timeout", "timeout"),
                            ("killed", "killed"),
                            ("aborted", "aborted"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("trigger", models.CharField(default="manual", max_length=20)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                ("target_version", models.CharField(blank=True, max_length=100)),
                ("browser", models.CharField(blank=True, max_length=40)),
                ("headed", models.BooleanField(default=False)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("artifacts_rel", models.CharField(blank=True, max_length=600)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("kill_requested", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="core.batch",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="core.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["test", "status"], name="core_run_test_id_0c21fd_idx"
                    ),
                    models.Index(
                        fields=["test", "-finished_at"],
                        name="core_run_test_id_c57f4c_idx",
                    ),
                    models.Index(fields=["status"], name="core_run_status_b9a383_idx"),
                ],
            },
        ),
    ]
