# Generated by Django 4.2.30 on 2026-08-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="browser",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Browser these scheduled runs simulate on; empty = config default",
                max_length=40,
            ),
        ),
    ]
