# Generated by Django 4.2.30 on 2026-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_schedule_browser"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="timings_json",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
