# Generated by Django 4.2.30 on 2026-08-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_run_timings_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="artifacts_index_json",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="run",
            name="artifacts_remote",
            field=models.BooleanField(default=False),
        ),
    ]
