# Generated by Django 4.2.30 on 2026-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_run_artifacts_index_json_run_artifacts_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="video_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "use the global setting"),
                    ("on", "always record video"),
                    ("off", "never record video"),
                ],
                default="",
                help_text="Per-test video override. Turn it off for tests that spend most of their time waiting: the .webm grows with wall-clock time whenever the page repaints (a countdown, a progress bar), so a 30-minute wait costs ~80 MB and shows nothing. The activity reel already covers those runs.",
                max_length=8,
            ),
        ),
    ]
