# Generated by Django 4.2.30 on 2026-08-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_test_video_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoadPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=600,
                        help_text="How long to keep applying load (wall clock).",
                    ),
                ),
                (
                    "concurrency",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How many copies of the test run at the same time -- each one is a real browser, so this is bounded by the machine's RAM and CPU, not by ambition.",
                    ),
                ),
                (
                    "ramp_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Start the copies gradually over this many seconds, so you can see where it starts to hurt.",
                    ),
                ),
                (
                    "think_time_seconds",
                    models.FloatField(
                        default=0,
                        help_text="Pause between iterations, imitating a human reading the page.",
                    ),
                ),
                (
                    "max_iterations",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 = no cap; stop only when the time is up.",
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=40)),
                (
                    "keep_artifacts",
                    models.BooleanField(
                        default=False,
                        help_text="Off by default. Hundreds of videos of the same test is gigabytes of disk to repeat what the timings already say.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="load_plans",
                        to="core.test",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="run",
            name="iteration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="run",
            name="minimal_artifacts",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="LoadRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "queued"),
                            ("running", "running"),
                            ("finished", "finished"),
                            ("killed", "killed"),
                            ("error", "error"),
                        ],
                        default="queued",
                        max_length=12,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=600)),
                ("concurrency", models.PositiveIntegerField(default=3)),
                ("ramp_seconds", models.PositiveIntegerField(default=0)),
                ("think_time_seconds", models.FloatField(default=0)),
                ("max_iterations", models.PositiveIntegerField(default=0)),
                ("browser", models.CharField(blank=True, max_length=40)),
                ("keep_artifacts", models.BooleanField(default=False)),
                ("baseline_seconds", models.FloatField(blank=True, null=True)),
                ("baseline_source", models.CharField(blank=True, max_length=40)),
                ("projected_iterations", models.PositiveIntegerField(default=0)),
                ("target_url", models.CharField(blank=True, max_length=500)),
                ("target_version", models.CharField(blank=True, max_length=100)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("kill_requested", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("summary_json", models.TextField(blank=True, default="{}")),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="core.loadplan",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_runs",
                        to="core.test",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="run",
            name="load_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="iterations",
                to="core.loadrun",
            ),
        ),
    ]
