# Generated by Django 4.2.30 on 2026-08-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_load_testing"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="security_json",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
