# Generated by Django 4.2.30 on 2026-08-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_run_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="test_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("python", "Python (def run(page, ctx))"),
                    ("ts", "TypeScript (@playwright/test)"),
                ],
                default="python",
                max_length=8,
            ),
        ),
    ]
