# Generated by Django 4.2.30 on 2026-09-25 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_test_test_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="core.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("manual", "manual"),
                    ("selection", "selection"),
                    ("group", "group"),
                    ("schedule", "schedule"),
                    ("terminal", "terminal"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
