from django.urls import path, re_path

from . import api, views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("tests/", views.tests_list, name="tests_list"),
    path("tests/new/", views.test_new, name="test_new"),
    path("tests/<str:test_id>/", views.test_detail, name="test_detail"),
    path("tests/<str:test_id>/edit/", views.test_edit, name="test_edit"),
    path("runs/", views.runs_list, name="runs_list"),
    path("runs/<int:run_id>/", views.run_detail, name="run_detail"),
    path("batches/<int:batch_id>/", views.batch_detail, name="batch_detail"),
    path("groups/", views.groups_list, name="groups_list"),
    path("groups/<int:group_id>/", views.group_detail, name="group_detail"),
    path("schedules/", views.schedules_list, name="schedules_list"),
    path("metrics/", views.metrics, name="metrics"),
    path("analytics/", views.analytics, name="analytics"),
    path("metrics/export.csv", views.metrics_csv, name="metrics_csv"),
    path("help/", views.help_page, name="help_page"),
    path("login/", views.login_page, name="login_page"),
    path("logout/", views.logout_page, name="logout_page"),
    path("backup/", views.backup_download, name="backup_download"),
    path("tests-export/", views.tests_export, name="tests_export"),
    path("tests-import/", views.tests_import, name="tests_import"),
    path("runs/<int:run_id>/report/", views.run_report, name="run_report"),
    path("security/", views.security_page, name="security_page"),
    path("settings/", views.settings_page, name="settings_page"),

    # load / performance testing
    path("load/", views.load_list, name="load_list"),
    path("load/new/", views.load_new, name="load_new"),
    path("load/<int:load_run_id>/", views.load_detail, name="load_detail"),

    # the built-in page-under-test, so everything works with zero external URLs
    path("demo/", views.demo, name="demo"),
    path("demo/submit/", views.demo_submit, name="demo_submit"),
    path("demo/login/", views.demo_login, name="demo_login"),
    path("demo/private/", views.demo_private, name="demo_private"),
    path("demo/logout/", views.demo_logout, name="demo_logout"),

    # artifacts (screenshots, video, trace, logs) under the results dir
    re_path(r"^artifacts/(?P<relpath>.+)$", views.artifact, name="artifact"),

    # JSON API (the UI's live parts)
    path("api/health/", api.health, name="api_health"),
    path("api/status/", api.status, name="api_status"),
    path("api/tests/run/", api.run_tests, name="api_run_tests"),
    path("api/groups/<int:group_id>/run/", api.run_group, name="api_run_group"),
    path("api/runs/<int:run_id>/live/", api.run_live, name="api_run_live"),
    path("api/runs/<int:run_id>/kill/", api.kill_run, name="api_kill_run"),
    path("api/batches/<int:batch_id>/kill/", api.kill_batch, name="api_kill_batch"),
    path("api/rescan/", api.rescan, name="api_rescan"),
    path("api/clock/", api.set_clock, name="api_set_clock"),
    path("api/load/preview/", api.load_preview, name="api_load_preview"),
    path("api/load/start/", api.load_start, name="api_load_start"),
    path("api/load/<int:load_run_id>/live/", api.load_live, name="api_load_live"),
    path("api/load/<int:load_run_id>/kill/", api.load_kill, name="api_load_kill"),
    path("api/load/plans/<int:plan_id>/delete/", api.load_plan_delete,
         name="api_load_plan_delete"),
    path("api/doctor/", api.doctor, name="api_doctor"),
    path("api/target-check/", api.target_check, name="api_target_check"),
    path("api/prune-results/", api.prune_results_api, name="api_prune_results"),
    path("api/runs/<int:run_id>/delete/", api.delete_run_data, name="api_delete_run"),
    path("api/tests/<str:test_id>/purge/", api.purge_test_data, name="api_purge_test"),
    path("api/purge-all/", api.purge_all_data, name="api_purge_all"),
    path("api/storage/check/", api.storage_check, name="api_storage_check"),
    path("api/storage/offload/", api.storage_offload, name="api_storage_offload"),
    path("api/schedules/<int:schedule_id>/toggle/", api.schedule_toggle,
         name="api_schedule_toggle"),
    path("api/schedules/<int:schedule_id>/delete/", api.schedule_delete,
         name="api_schedule_delete"),
    path("recorder/", views.recorder_page, name="recorder_page"),
    path("api/remote-rec/start/", api.remote_rec_start, name="api_remote_rec_start"),
    path("api/remote-rec/status/", api.remote_rec_status, name="api_remote_rec_status"),
    path("api/remote-rec/frame/", api.remote_rec_frame, name="api_remote_rec_frame"),
    path("api/remote-rec/input/", api.remote_rec_input, name="api_remote_rec_input"),
    path("api/remote-rec/inspect/", api.remote_rec_inspect, name="api_remote_rec_inspect"),
    path("api/remote-rec/add-step/", api.remote_rec_add_step, name="api_remote_rec_add_step"),
    path("api/remote-rec/stop/", api.remote_rec_stop, name="api_remote_rec_stop"),
    path("api/remote-rec/apply/", api.remote_rec_apply, name="api_remote_rec_apply"),
    path("api/remote-rec/clear/", api.remote_rec_clear, name="api_remote_rec_clear"),
    path("api/recorder/start/", api.recorder_start, name="api_recorder_start"),
    path("api/recorder/status/", api.recorder_status, name="api_recorder_status"),
    path("api/recorder/stop/", api.recorder_stop, name="api_recorder_stop"),
]
